name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Étape 1 : compilation Kotlin seule, en mode verbeux, pour récupérer l'erreur précise
      - name: Compile Kotlin (diagnostic)
        run: ./gradlew :app:compileDebugKotlin --no-daemon --info --stacktrace --warning-mode all

      # Étape 2 : build complet APK si la compilation Kotlin passe
      - name: Build Debug APK
        if: success()
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      # Logs & rapports utiles (toujours uploadés même en cas d'échec)
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            **/build/reports/**
            **/build/tmp/**
            **/build/outputs/logs/**
            **/build/kotlin/**

      # APK (uniquement si build OK)
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SamoHammer-debug
          path: app/build/outputs/apk/debug/app-debug.apk
