name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 0) Full clean pour purger les références de ressources/stubs en cache
      - name: Clean
        run: ./gradlew clean --no-daemon --no-build-cache --stacktrace

      # 1) Diagnostic ressources (AAPT) — si ça casse ici, on aura la ligne précise
      - name: Process resources (diagnostic)
        run: ./gradlew :app:processDebugResources --no-daemon --no-build-cache --info --stacktrace --warning-mode all

      # 2) Diagnostic Kotlin (ULTRA verbeux) — donnera les lignes "e: fichier:ligne"
      - name: Compile Kotlin (diagnostic)
        if: success()
        run: ./gradlew :app:compileDebugKotlin \
             --no-daemon --no-build-cache --rerun-tasks \
             --info --debug --stacktrace --warning-mode all \
             -Pkotlin.compiler.execution.strategy=in-process \
             -Dkotlin.incremental=false

      # 3) Build APK si tout est OK
      - name: Build Debug APK
        if: success()
        run: ./gradlew assembleDebug --no-daemon --no-build-cache --stacktrace

      # 4) Rapports utiles (toujours)
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            **/build/reports/**
            **/build/tmp/**
            **/build/outputs/logs/**
            **/build/intermediates/**
            **/build/kotlin/**

      # 5) APK (si build OK)
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SamoHammer-debug
          path: app/build/outputs/apk/debug/app-debug.apk
